---
- hosts: windows
  tasks:
    - name: Installation GLPI
      block:
          - name: Install GLPI
            win_package:
              path: https://github.com/glpi-project/glpi-agent/releases/download/1.4/GLPI-Agent-1.4-x64.msi
              state: present
              arguments: SERVER=192.16.10.10