---
- name: "Windows AD Join"
  hosts: windows
  tasks:
    - name: "Join Domain"
      win_domain_membership:
        dns_domain_name: spa24.iut.
        domain_admin_user: admin
        domain_admin_password: lego-Constructions
        state: domain
      register: domain_state
    - win_reboot:
      when: domain_state.reboot_required